// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class CreateUserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        // Force specific GeckoDriver version compatible with Firefox ESR
        WebDriverManager.firefoxdriver().driverVersion("0.35.0").setup();

        // Configure Firefox options to use ESR explicitly
        FirefoxOptions options = new FirefoxOptions();
        options.setBinary("/usr/bin/firefox-esr");

        driver = new FirefoxDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void createUserTest() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(960, 1048));
        driver.findElement(By.linkText("Create new account")).click();
        driver.findElement(By.id("user_first_name")).click();
        driver.findElement(By.id("user_first_name")).sendKeys("Mohammed");
        driver.findElement(By.id("user_last_name")).sendKeys("Yasin");
        driver.findElement(By.id("user_email")).sendKeys("bsse1406@iit.du.ac.bd");
        driver.findElement(By.id("user_password")).sendKeys("1406");
        driver.findElement(By.id("user_password_confirmation")).sendKeys("1406");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).sendKeys("Yasin1406");
        driver.findElement(By.id("user_password_confirmation")).click();
        driver.findElement(By.id("user_password_confirmation")).sendKeys("Yasin1406");
        driver.findElement(By.cssSelector("button")).click();
    }


    @Test
    public void signUpWithExistingEmail() {
        driver.get("http://localhost:4000/sign_up");
        driver.manage().window().setSize(new Dimension(960, 1048));
        driver.findElement(By.id("user_first_name")).click();
        driver.findElement(By.id("user_first_name")).sendKeys("Mohammed");
        driver.findElement(By.id("user_last_name")).sendKeys("Yasin");
        driver.findElement(By.id("user_email")).sendKeys("bsse1406@iit.du.ac.bd");
        driver.findElement(By.id("user_password")).sendKeys("yasin");
        driver.findElement(By.id("user_password_confirmation")).sendKeys("yasin");
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("Email already taken"));
    }
}